from PyQt5 import QtCore, QtGui, QtWidgets

takeOff = False

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Speed = QtWidgets.QLabel(self.centralwidget)
        self.Speed.setGeometry(QtCore.QRect(71, 31, 59, 16))
        self.Speed.setObjectName("Speed")
        self.Alt = QtWidgets.QLabel(self.centralwidget)
        self.Alt.setGeometry(QtCore.QRect(196, 31, 47, 16))
        self.Alt.setObjectName("Alt")
        self.SpeedInfo = QtWidgets.QLabel(self.centralwidget)
        self.SpeedInfo.setGeometry(QtCore.QRect(137, 31, 61, 16))
        self.SpeedInfo.setText("")
        self.SpeedInfo.setObjectName("SpeedInfo")
        self.AltInfo = QtWidgets.QLabel(self.centralwidget)
        self.AltInfo.setGeometry(QtCore.QRect(245, 31, 71, 16))
        self.AltInfo.setText("")
        self.AltInfo.setObjectName("AltInfo")
        self.Kurs = QtWidgets.QLabel(self.centralwidget)
        self.Kurs.setGeometry(QtCore.QRect(314, 31, 31, 16))
        self.Kurs.setObjectName("Kurs")
        self.VSpeedInfo = QtWidgets.QLabel(self.centralwidget)
        self.VSpeedInfo.setGeometry(QtCore.QRect(528, 31, 91, 16))
        self.VSpeedInfo.setText("")
        self.VSpeedInfo.setObjectName("VSpeedInfo")
        self.VSpeed = QtWidgets.QLabel(self.centralwidget)
        self.VSpeed.setGeometry(QtCore.QRect(433, 31, 88, 16))
        self.VSpeed.setObjectName("VSpeed")
        self.KursInfo = QtWidgets.QLabel(self.centralwidget)
        self.KursInfo.setGeometry(QtCore.QRect(349, 31, 81, 16))
        self.KursInfo.setText("")
        self.KursInfo.setObjectName("KursInfo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1, 120, 231, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(210, 210, 210);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 320, 110, 26))
        self.pushButton.setStyleSheet("background-color: rgb(210, 210, 210);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(234, 120, 115, 31))
        self.label_2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(234, 155, 115, 31))
        self.label_3.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1, 155, 231, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(210, 210, 210);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlightGear_Interface"))
        self.Speed.setText(_translate("MainWindow", "Скорость:"))
        self.Alt.setText(_translate("MainWindow", "Высота:"))
        self.Kurs.setText(_translate("MainWindow", "Курс:"))
        self.VSpeed.setText(_translate("MainWindow", "Вер. Скорость:"))
        self.label.setText(_translate("MainWindow", "Введите необходимую скорость:"))
        self.pushButton.setText(_translate("MainWindow", "TakeOff"))
        self.label_4.setText(_translate("MainWindow", "Введите необходимую высоту:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
